# Generated by Django 3.2.8 on 2021-10-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('summary', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('script_title_1', models.CharField(max_length=254)),
                ('script_1', models.URLField(max_length=2000)),
                ('codepen_title_1', models.CharField(blank=True, max_length=254, null=True)),
                ('codepen_data_slug_hash_1', models.CharField(blank=True, max_length=254, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(to='basics.Category')),
            ],
        ),
    ]
